#!/usr/bin/env python3
"""Auto-generated by compile_hooks.py — DO NOT EDIT MANUALLY.

Regenerate: python -m automation_engine compile-hooks
Source hash: 2fbc41593cea355b
Rules: 6
"""
import json
import re
import signal
import sys
from datetime import date

# 1秒タイムアウト（ハング防止）
try:
    signal.alarm(1)
except (AttributeError, ValueError):
    pass  # Windows では signal.alarm 未サポート


def _today() -> str:
    return date.today().isoformat()


def main():
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)  # パース失敗はフェイルオープン

    tool = data.get("tool_name", "")
    inp = data.get("tool_input", {})

    # === コンテンツ取得 ===
    content = ""
    file_path = ""

    if tool == "Write":
        content = inp.get("content", "")
        file_path = inp.get("file_path", "")

    elif tool == "Edit":
        new_string = inp.get("new_string", "")
        file_path = inp.get("file_path", "")
        old_string = inp.get("old_string", "")
        # 仮想置換: ファイル全体を検証（Edit の文脈制限対策）
        if file_path and old_string:
            try:
                full = open(file_path).read()
                content = full.replace(old_string, new_string, 1)
            except (FileNotFoundError, PermissionError):
                content = new_string
        else:
            content = new_string

    elif tool == "Bash":
        cmd = inp.get("command", "")
        # Bash ツール回避対策: ファイル書き込みコマンドの検出
        if re.search(r"(?:echo|printf|cat|python|perl|ruby|node)\s.*(?:>|>>)\s", cmd):
            print(
                "\u26a0 ファイル書き込みには Write/Edit ツールを使用してください。"
                " Bash での直接書き込み（echo > file）は hooks 検証をバイパスします。",
                file=sys.stderr,
            )
            sys.exit(2)
        if re.search(r"\bsed\b.*-i", cmd):
            print(
                "\u26a0 ファイル編集には Edit ツールを使用してください。"
                " sed -i は hooks 検証をバイパスします。",
                file=sys.stderr,
            )
            sys.exit(2)
        if re.search(r"\btee\b\s+(?!/dev/null)", cmd):
            print(
                "\u26a0 ファイル書き込みには Write/Edit ツールを使用してください。"
                " tee は hooks 検証をバイパスします。",
                file=sys.stderr,
            )
            sys.exit(2)
        if re.search(r"\bawk\b.*-i\s*inplace", cmd):
            print(
                "\u26a0 ファイル編集には Edit ツールを使用してください。"
                " awk -i inplace は hooks 検証をバイパスします。",
                file=sys.stderr,
            )
            sys.exit(2)
        # GP-020: gh issue edit/view が PR を誤操作するのを防止
        # gh issue edit は引数順序が多様なため、サブコマンド部分のみで無条件ブロック
        if re.search(r"gh\s+issue\s+edit\b", cmd):
            print(
                "\u26a0 GP-020: gh issue edit を検出。"
                " GitHub では PR と Issue が番号を共有するため、"
                " gh issue edit は PR のタイトル・本文も上書きする危険があります。"
                " 代わりに以下の手順で操作してください:\n"
                "   1. 対象が Issue か確認: gh api repos/OWNER/REPO/issues/N --jq .pull_request\n"
                "      (null=Issue, オブジェクト=PR)\n"
                "   2. Issue であることを確認後: gh api repos/OWNER/REPO/issues/N -X PATCH -f title=... -f body=...",
                file=sys.stderr,
            )
            sys.exit(2)
        # GP-014: gh pr merge direct execution prevention
        if re.search(r"gh\s+pr\s+merge\b", cmd):
            print(
                "\u26a0 GP-014: gh pr merge direct execution blocked."
                " Use /merge skill instead (CI check + merge + cleanup atomically).",
                file=sys.stderr,
            )
            sys.exit(2)
        sys.exit(0)

    else:
        sys.exit(0)

    if not content:
        sys.exit(0)

    # === ルール検証 ===
    # === GN-001 ===
    if re.search(r'\.(html|htm|md|txt|csv)$', file_path) and re.search(r'\$\d', content):
        print("\u26a0 GN-001 違反: ドル記号禁止。¥ に置換してください。", file=sys.stderr)
        print("  修正方法: $ を ¥ に置換", file=sys.stderr)
        sys.exit(2)

    # === SL-028 ===
    if re.search(r'\.html$', file_path) and re.search(r'box-shadow\s*:', content):
        print("\u26a0 SL-028 違反: box-shadow 全面禁止（Playwright PDF で矩形アーティファクト化）。border で代替。", file=sys.stderr)
        print("  修正方法: box-shadow を削除し border: 1px solid #e0e8e6 等で代替", file=sys.stderr)
        sys.exit(2)

    # === SL-029 ===
    if re.search(r'\.html$', file_path) and re.search(r'font-size\s*:\s*\d+(?:\.\d+)?px', content):
        print("\u26a0 SL-029 違反: font-size に直書き px 値禁止。var(--fs-xxx) トークンを使用してください。", file=sys.stderr)
        print("  修正方法: font-size: 11px → font-size: var(--fs-body)", file=sys.stderr)
        sys.exit(2)

    # === SL-034 ===
    if re.search(r'\.html$', file_path) and re.search(r'gap\s*:\s*0(?:px)?\s*[;\"]', content):
        print("\u26a0 SL-034 違反: gap:0 は原則禁止。最低 gap:2px を設定してください。", file=sys.stderr)
        print("  修正方法: gap:0 → gap:2px", file=sys.stderr)
        sys.exit(2)

    # === SL-035 ===
    if re.search(r'\.html$', file_path) and re.search(r'margin-bottom\s*:\s*[01]px', content):
        print("\u26a0 SL-035 違反: margin-bottom:0-1px は禁止。文脈別最小マージンを確認してください。", file=sys.stderr)
        print("  修正方法: margin-bottom: 0 → margin-bottom: 4px（セクション見出し→本文の最低値）", file=sys.stderr)
        sys.exit(0)

    # === SL-051 ===
    if re.search(r'\.html$', file_path) and re.search(r'class="[^"]*(?:flex |grid |text-(?:sm|lg|xl)|bg-(?:white|gray|blue))', content):
        print("\u26a0 SL-051 違反: Tailwind/utility クラス禁止。インラインCSS を使用してください。", file=sys.stderr)
        print("  修正方法: class=\"flex\" → style=\"display: flex;\"", file=sys.stderr)
        sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:
        # フェイルオープン: hook 自体のエラーでは通過
        print(f"[Hook Warning] validate_rules.py error: {e}", file=sys.stderr)
        sys.exit(0)
